### ISSUE TITLE
Did the class InfiniAttention repeat_kv for twice？

### ISSUE THREAD

**Issue by Yukino256** [jlamprou/Infini-Attention#5]
In the file modeling_qwen_transformers.py， line 545 and line 560；
It seems like a mistake， or these 2 repeat performs different function？

**Comment by jlamprou** [comment]
No mistake, we are just following the original Qwen Attention class, we repeat_kv for Key states and for Value states, if you notice we repeat kv it's not the same line twice
```python
        key_states = repeat_kv(key_states, self.num_key_value_groups)
        value_states = repeat_kv(value_states, self.num_key_value_groups)
```
